server:
  port: 8083
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  thymeleaf:
    encoding: utf-8
    mode: html5
    content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/static