server:
  port: 8083
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: prod
  thymeleaf:
    encoding: utf-8
    mode: html5
    content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl
    username: root
    password: 314159
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/static